id: PF7980EB7
initial_creation_type: input
source_metadata:
  title: Ga Rabjampa Kunga Yeshe
  language: bo
  description: 'Texts by and about the Sakya scholar Ga Rabjampa Kunga Yeshe (sga
    rab ''byams pa kun dga'' ye shes, 1397–1470), founder of Tharlam Monastery:'
  volume:
    3df731c7fd47465aba1be53cbabc8974:
      title: 'The Excellent Path to Enlightenment: An Aspiration Towards the Mahāyāna
        Mind Training'
      parent: Aspiration Prayers
    69358734350f4af1b62e6eb27108ecbb:
      title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural
        Traditions
      parent: Praise
created_at: '2022-02-28T23:20:32.290727'
last_modified_at: '2022-02-28T23:20:32.290730'
statistics:
  total_words: 1537
  total_non_words: 103
quality:
  non_words_ratio: 0.07
